global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: server-debug
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8000
  - job_name: server-docker
    metrics_path: /metrics
    static_configs:
      - targets:
          - server:8080
